print(float("1, 3"))


"""
The ValueError occurs when you use the float() 
function to convert a string to a float, but 
the string contains characters that cannot be 
interpreted as a float. 



"""